import { IApp } from "../types";

const apps: IApp[] = [
  {
    name: "Bin2Dec",
    desc: "Binary-to-Decimal number converter",
    url: "/bin2dec-app",
    level: "1-Beginner",
  },
  {
    name: "Border Radius Previewer",
    desc: "Preview how CSS3 border-radius values affect an element",
    url: "/border-radius-previewer",
    level: "1-Beginner",
  },
  {
    name: "Calculator",
    desc: "Calculator",
    url: "/calculator-app",
    level: "1-Beginner",
  },
  {
    name: "Christmas Lights",
    desc: "Simulate a string of Christmas lights",
    url: "/christmas-lights-app",
    level: "1-Beginner",
  },
  {
    name: "Cause Effect App",
    desc: "Click list item to display item details",
    url: "/cause-effect-app",
    level: "1-Beginner",
  },
  {
    name: "Color Cycle",
    desc: "Cycle a color value through incremental changes",
    url: "/color-cycle-app",
    level: "1-Beginner",
  },
  {
    name: "Countdown Timer App",
    desc: "Event Countdown timer",
    url: "/countdown-timer-app",
    level: "1-Beginner",
  },
  {
    name: "CSV2JSON App",
    desc: "CSV to JSON converter",
    url: "/csv2json-app",
    level: "1-Beginner",
  },
  {
    name: "Dollars To Cents App",
    desc: "Convert dollars to cents",
    url: "/dollars-to-cents-app",
    level: "1-Beginner",
  },
  {
    name: "Dynamic CSSVar App",
    desc: "Dynamically change CSS variable settings",
    url: "/dynamic-cssvar-app",
    level: "1-Beginner",
  },
  {
    name: "First DB App",
    desc: "Your first Database app!",
    url: "/first-db-app",
    level: "1-Beginner",
  },
  {
    name: "Flip Image App",
    desc: "Change the orientation of images across two axes",
    url: "/flip-image-app",
    level: "1-Beginner",
  },
  {
    name: "GitHub Status App",
    desc: "Display Current GitHub Status",
    url: "/github-status-app",
    level: "1-Beginner",
  },
  {
    name: "Hello App",
    desc: "User native language greeting",
    url: "/hello-app",
    level: "1-Beginner",
  },
  {
    name: "IOT Mailbox App",
    desc: "Use callbacks to check your snail mail",
    url: "/iot-mailbox-app",
    level: "1-Beginner",
  },
  {
    name: "Javascript Validation With Regex",
    desc: "Script to validate inputs entered by a user using RegEx",
    url: "/javascript-validation-with-regex",
    level: "1-Beginner",
  },
  {
    name: "JSON2CSV App",
    desc: "JSON to CSV converter",
    url: "/json2csv-app",
    level: "1-Beginner",
  },
  {
    name: "Key Value App",
    desc: "Keyboard Event Values",
    url: "/key-value-app",
    level: "1-Beginner",
  },
  {
    name: "Lorem Ipsum Generator",
    desc: "Generate lorem ipsum placeholder text",
    url: "/lorem-ipsum-generator",
    level: "1-Beginner",
  },
  {
    name: "Notes App",
    desc: "Create an online note pad",
    url: "/notes-app",
    level: "1-Beginner",
  },
  {
    name: "Pearson Regression App",
    desc: "Calculate the correlation coefficient for two sets of data",
    url: "/pearson-regression-app",
    level: "1-Beginner",
  },
  {
    name: "Pomodoro Clock",
    desc: "Task timer to aid personal productivity",
    url: "/pomodoro-clock",
    level: "1-Beginner",
  },
  {
    name: "Product Landing Page",
    desc: "Showcase product details for possible buyers",
    url: "/product-landing-page",
    level: "1-Beginner",
  },
  {
    name: "Quiz App",
    desc: "Test your knowledge by answering questions",
    url: "/quiz-app",
    level: "1-Beginner",
  },
  {
    name: "Recipe App",
    desc: "Recipe",
    url: "/recipe-app",
    level: "1-Beginner",
  },
  {
    name: "Random Meal Generator",
    desc: "Generate random meals",
    url: "/random-meal-generator",
    level: "1-Beginner",
  },
  {
    name: "Random Number Generator",
    desc: "Generate random number between range.",
    url: "/random-number-generator",
    level: "1-Beginner",
  },
  {
    name: "Roman-to-Decimal Converter",
    desc: "Convert Roman to Decimal numbers",
    url: "/roman-to-decimal-converter",
    level: "1-Beginner",
  },
  {
    name: "Slider Design",
    desc: "Display images using a slider control",
    url: "/slider-design",
    level: "1-Beginner",
  },
  {
    name: "Stopwatch App",
    desc: "Count time spent on activities",
    url: "/stopwatch-app",
    level: "1-Beginner",
  },
  {
    name: "True or False App",
    desc: "Identify the result of a conditional comparison",
    url: "/true-or-false-app",
    level: "1-Beginner",
  },
  {
    name: "Vigenere Cipher",
    desc: "Encrypt text using the Vigenere Cypher",
    url: "/vigenere-cipher",
    level: "1-Beginner",
  },
  {
    name: "Windchill App",
    desc: "Calculate the windchill factor from an actual temperature",
    url: "/windchill-app",
    level: "1-Beginner",
  },
  {
    name: "Word Frequency App",
    desc: "Calculate word frequency in a block of text",
    url: "/word-frequency-app",
    level: "1-Beginner",
  },
  {
    name: "Weather App",
    desc: "Get the temperature, weather condition of a city.",
    url: "/weather-app",
    level: "1-Beginner",
  },
];

export default apps;
